GET http://localhost:3000/api/todos/

###

POST http://localhost:3000/api/todos
Content-Type: application/json

{
  "text": "Get greens"
}

### 

DELETE http://localhost:3000/api/todos/628d9d96565ceb6f361ce6ac

###

PUT http://localhost:3000/api/todos/628d30d6481fe29533a3914c